### ISSUE TITLE
Add feature to include information from TOML

### ISSUE THREAD

**Issue by astropenguin** [astropenguin/xarray-custom#8]
Add feature to load a TOML file that contains attributes' information.
For example, the following custom DataArray class:

```python
@dataarrayclass(accessor='img')
class Image:
    """DataArray class to represent images."""

    dims = 'x', 'y'
    dtype = float
    x: ctype('x', int) = 0
    y: ctype('y', int) = 0

    def normalize(self):
        return self / self.max()
```

should be equivalent to the following code and the TOML file.

```python
@dataarrayclass(accessor='img')
@include("attributes.toml")
class Image:
    def normalize(self):
        return self / self.max()
```

```toml
# attributes.toml

desc = "DataArray class to represent images."
dims = [ "x", "y" ]
dtype = "float"

[coords.x]
dims = "x"
dtype = "int"
default = 0

[coords.y]
dims = "x"
dtype = "int"
default = 0
```
